spirng: 
 profiles: 
  active: 
   - dev

---
spring: 
 profiles: dev
  application:
   name: microservicecloud-config-jx-dev

---
spring: 
 profiles: dev
  application:
   name: microservicecloud-config-jx-test