spring:
 profiles:
  active:
   - dev


---

spring:
 profiles: dev
 application:
  name: microservicecloud-cofig-client

eureka:
 client:
  service-url:
   defaultZone: http//eureka-dev.com:7001/eureka/
server:
  port: 8202
---   
spring:
 profiles: test
 application:
  name: microservicecloud-cofig-client

eureka:
 client:
  service-url:
   defaultZone: http//eureka-dev.com:7001/eureka/
server:
  port: 8203