spring:
 profiles:
  active:
   - dev

---   
server:
 port: 8201
 
spring:
 profiles: dev
 appliction:
  name: microservicecloud-cofig-client

euraka:
 client:
  service-url:
   defaultZone: http//eureka-dev.com:7001/eureka/
---   
server:
 port: 8202
 
spring:
 profiles: test
 appliction:
  name: microservicecloud-cofig-client

euraka:
 client:
  service-url:
   defaultZone: http//eureka-test.com:7001/eureka/